spring.application.name=Authentication-Authorization

server.addres=0.0.0.0
server.port=1010

spring.security.user.name=root
spring.security.user.password=root

spring.datasource.url=jdbc:mysql://localhost:3307/AuthDB
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.datasource.url=jdbc:h2:mem:AA
#spring.datasource.username=root
#spring.datasource.password=root
#pring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

